#!/bin/bash
echo "PARA CREAR .EXE REAL DE WINDOWS:"
echo "================================"
echo ""
echo "OPCION 1 - Wine (en este mismo Linux):"
echo "  sudo apt install wine"
echo "  # Luego usar el script con Wine"
echo ""
echo "OPCION 2 - GitHub Actions (en la nube):"
echo "  # Subir código a GitHub"
echo "  # GitHub compila automáticamente"
echo ""
echo "OPCION 3 - Docker (sin Wine):"
echo "  sudo apt install docker.io"
echo "  # Usar contenedor Windows"
echo ""
echo "OPCION 4 - Windows real:"
echo "  # Llevar código a PC Windows"
echo "  # pip install pyinstaller mysql-connector-python"
echo "  # pyinstaller --onefile --windowed app.py"
echo ""
echo "El ejecutable actual solo funciona en Linux."
